name: Test CF CLI Action

on:
  push:
    branches: [main]
    paths:
      - '.github/actions/setup-cf-cli/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/actions/setup-cf-cli/**'
  workflow_dispatch:
    inputs:
      cf_version:
        description: 'CF CLI version to test'
        required: false
        default: 'latest'

jobs:
  quick-test:
    name: Quick Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup CF CLI (latest)
        uses: .//.github/actions/setup-cf-cli
        with:
          version: 'latest'
          
      - name: Smoke test
        run: |
          echo "🧪 Quick smoke test..."
          cf version
          echo "✅ CF CLI is working!"

  test-versions-and-cache:
    name: Test Versions & Cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_case:
          - { version: 'latest', name: 'latest' }
          - { version: '8.7.10', name: 'specific' }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup CF CLI (${{ matrix.test_case.name }})
        id: cf-setup
        uses: .//.github/actions/setup-cf-cli
        with:
          version: ${{ matrix.test_case.version }}
          cache-key-suffix: '-${{ matrix.test_case.name }}'
          
      - name: Verify CF CLI installation
        run: |
          echo "Testing CF CLI ${{ matrix.test_case.version }}..."
          cf version
          which cf
          
          # Verify specific version if not latest
          if [ "${{ matrix.test_case.version }}" = "8.7.10" ]; then
            cf version | grep -q "8.7.10" && echo "✅ Correct version installed" || exit 1
          fi
          
      - name: Test basic commands
        run: |
          cf help > /dev/null
          cf curl /v2/info || echo "Expected to fail without login"
          
      - name: Show outputs
        run: |
          echo "CF CLI Version: ${{ steps.cf-setup.outputs.cf-version }}"
          echo "Cache Hit: ${{ steps.cf-setup.outputs.cache-hit }}"

  test-cache-behavior:
    name: Test Cache Behavior
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: First CF CLI setup (should download)
        id: cf-setup-first
        uses: .//.github/actions/setup-cf-cli
        with:
          version: 'latest'
          cache-key-suffix: '-cache-test'
          
      - name: Verify first installation
        run: |
          echo "First installation - Cache Hit: ${{ steps.cf-setup-first.outputs.cache-hit }}"
          cf version
          
      - name: Second CF CLI setup (should use cache)
        id: cf-setup-second
        uses: .//.github/actions/setup-cf-cli
        with:
          version: 'latest'
          cache-key-suffix: '-cache-test'
          
      - name: Verify cache usage
        run: |
          echo "Second installation - Cache Hit: ${{ steps.cf-setup-second.outputs.cache-hit }}"
          cf version
          # Note: Cache hit might still be 'false' in same job due to GitHub Actions behavior

  test-workflow-input:
    name: Test Workflow Input Version
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup CF CLI with input version
        id: cf-setup-input
        uses: .//.github/actions/setup-cf-cli
        with:
          version: ${{ github.event.inputs.cf_version }}
          
      - name: Test input version
        run: |
          echo "Testing CF CLI version from workflow input..."
          cf version
          echo "Requested: ${{ github.event.inputs.cf_version }}"
          echo "Installed: ${{ steps.cf-setup-input.outputs.cf-version }}"
